### ISSUE TITLE
Transmitting information on synchrnoy of input clocks into FMU

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1125] opened 2020-08-19 18:15 UTC
An importer can detect if sub-sampled, super-Sampled, and conditional clocks of any kind entering to an FMU are synchronous or not. An importer can detect synchrony among rational  interval clocks, so the importer can detect if rational Clocks entering in an FMU are synchronous or not. Real interval clocks and Boolean clocks (clock for state events) cannot be synchronized (unless for example one is the sub-sampled of another).
The importer MUST indicate the FMU  whether the input clocks are synchronous by setting the simultaneous clocks ticks at the "very same SetClock()". This would allow handling the cases like this example (taken from Modelica Synchronous section  16.5.2 Sub-clock conversion operators):

 model NoClockVsSampleHold
  Clock clk1 = Clock(0.1);
  Clock clk2 = subSample(clk1,2);
  Real x(start=0), y(start=0), z(start=0);
equation
  when clk1 then
    x = previous (x) + 0.1;
  end when;
  when clk2 then
    y = noClock (x); // most recent value of x
    z = sample (hold(x)); // left limit of x (infinitesimally delayed)!
  end when;
end NoClockVsSampleHold;

So if clk1 and clk2 are really set synchronous, the importer can let the FMU know and the FMU can treat it correctly.
Otherwise, there is no way to handle this example correctly.

Synchrony is a necessary information on an FMU input clocks that can only provided by the importer.
Note than two simultaneous clocks are not necessarily synchronous, for example, in this example
  Clock clk3 = Clock(0.1);
  Clock clk4 = Clock(0.1);
clk3 and clk4 are not synchronous. Note that declaring clk3 and clk4 as synchronous might be harmless, you just lose the information. But if the importer does not declare clk1 and clk2 as synchronous, the result would be false.

**Comment by andreas-junghanns** [comment] 2020-08-20 09:15
OK, I agree, but if that is not obvious, can you suggest a PR where this is clarified in the description of synchronous clocks?

**Comment by masoud-najafi** [comment] 2020-08-21 08:26
Others may propose a better solution than this one. Because for other SetXXX, doing
setXXX([v1,v2])  
should not result in a different result than by doing
setXXX(v1)
setXXX(v2)
Here the result of  
SetClock([clk1,clk2]) may be different than 
SetClock(clk1);
SetClock(clk2);

**Comment by TorstenBlochwitz** [comment] 2020-08-27 12:43
If one FMU exposes two input clocks, they are handled by the importer as two separated input clocks. If they (by design or by accident) tick at the same instance of superdense time in Event Mode or not is not relevant for the FMU!

If the two clocks depend on each other (for example clock2 is a subclock of clock1), then only clock1 is exposed as input clock by the FMU.

If two independent clocks tick at the same instance of the superdense time the importer has to activate them in Event Mode before fmi3NewDiscreteStates is called.

**Comment by masoud-najafi** [comment] 2020-08-27 13:12
> If the two clocks depend on each other (for example clock2 is a subclock of clock1), then only clock1 is exposed as input clock by the FMU.
> 
But how can one handle the above example where the FMU performs different jobs on ticks of clk1 and clk2 (clk2 is a subclock of clk1)? Do you means, the FMU should be exported in such a way that only clk1 is exposed as input and clk2  is reproduced again (subsampled) inside FMU?
Suppose the FMU is exported with two input clocks that performs three different jobs on clk1 (alone), clk2 (alone) and clk1& clk2 (synchronous).  We may not exclude this use case.

**Comment by andreas-junghanns** [comment] 2020-08-27 17:15
> 
> 
> > If the two clocks depend on each other (for example clock2 is a subclock of clock1), then only clock1 is exposed as input clock by the FMU.
> 
> But how can one handle the above example where the FMU performs different jobs on ticks of clk1 and clk2 (clk2 is a subclock of clk1)? Do you means, the FMU should be exported in such a way that only clk1 is exposed as input and clk2 is reproduced again (subsampled) inside FMU?
> Suppose the FMU is exported with two input clocks that performs three different jobs on clk1 (alone), clk2 (alone) and clk1& clk2 (synchronous). We may not exclude this use case.

If the cases clk1, clk2 and clk1&clk2 are different, then clk2 is not a true subclock of clk1.

I think this is clear - if you agree, Masoud, please close this ticket.

**Comment by masoud-najafi** [comment] 2020-08-28 06:48
> If the cases clk1, clk2 and clk1&clk2 are different, then clk2 is not a true subclock of clk1.
> 
> I think this is clear - if you agree, Masoud, please close this ticket.
Just consider this Modelica example (There are also examples from other synchronous languages):
Clock clk0 = Clock(1);
Clock clk1 = subSample(clk1,2);
Clock clk2 = subSample(clk1,3);

The FMU receives clk1 and clk2 as clock input in the above example:

clk1 ticks at 0, 2, 4, 6, 8,10, 12, 14
clk2 ticks at 0, 3, 6, 9, 12, 15
clk1 & clk2 are synchronous at 0, 6, 12, ...

For each of these situations you may need to specify different job should be done in the FMU. This is an important and may need to be clearly defined. If we do not want to handle it we need just say it clearly.

**Comment by andreas-junghanns** [comment] 2020-08-28 07:12
I think your example should read (and is a different example from the one previously, right?):
Clock clk0 = Clock(1);
Clock clk1 = subSample(clk0,2);
Clock clk2 = subSample(clk0,3);

I still think this requires only one clock to be exposed: clk0.
The subclocks clk1 and clk2 can be internally derived by simple counters.
Why should we complicate the interface for such cases?

**Comment by masoud-najafi** [comment] 2020-08-28 07:48
Yes, exposing only clk0 is a solution to THIS problem. But, we lose the generality. Also, this may not be possible in general. What if, for example, subsample ratios (2 and 3)  are needed to be changed outside of the FMU?

**Comment by andreas-junghanns** [comment] 2020-08-28 10:16
> 
> 
> Yes, exposing only clk0 is a solution to THIS problem. But, we lose the generality. Also, this may not be possible in general. What if, for example, subsample ratios (2 and 3) are needed to be changed outside of the FMU?

Then, these clocks are not subclocks. subclocks have fixed ratios. If the ratio is not fixed, the clocks are not periodic.

**Comment by TorstenBlochwitz** [comment] 2020-08-28 13:07
I agree to Andreas. Subclocks stay inside of the FMU and are handled there, only "Independent" clocks are exposed.

**Comment by masoud-najafi** [comment] 2020-08-28 13:22
This is one way of implementation. What if the exporter want to expose these two clocks? If the exporter exposes these two clocks and relies on external synchronous clocks, the result would be incorrect.

I we want to accept  "only "Independent" clocks.", then we should say it somewhere in the standard and give some rationals for forbidding it.

**Closed** 2020-08-31 08:52 UTC
