### ISSUE TITLE
Scrap event information at fmiEnterEventMode

### ISSUE THREAD

**Issue by KarlWernersson** [modelica/fmi-standard#1042] opened 2020-05-29 13:14 UTC
I apoligze for missing this earlier.

So a change from FMI 2 is that you now can provide information about the event type when you enter Event mode. By the arguments inputEvent, stepEvent, rootsFound, timeEvent.

I see a couple of problems with this. 

1. Besides time event all other events can be triggered by reactions to other events. So even if you start with a time event you can easily soon have all other events active in your event iteration, that if we want this information it should be in the newDiscreteState function and not the enter Event mode. Or alteals all but time event.

2. >  [These arguments are not mutually exclusive and may all be fmi3False if the caller cannot provide this information.]

This statement makes the information useless as the FMU cannot be sure that the information is correct and therefore needs to check for all event types any way.

3. If we make it mandatory we put allot of extra strain on the master, for what gain?

4. A stepEvent could be triggered by other events but we have no way of signaling this to the master so it can not return that information to the fmu if it happens during event iteration. In fmi2 this is handled internally while calling newDiscreteStates without any problem.. 

5. Any input changes are input events during event iteration. To really optimize we should maybe specify which input it is that changers?
A more practical optimization is to avoid calling newDiscreteStates on an FMU that don't have input changes and is not currently iterating internal events. (I.e an FMU with all the event arguments false)

6. If one have to provide which state event that is active through the rootsFound event iteration would certainly need more iterations. One can look at the CoupledClutches in the modelica standard library,  (image of the model, 4 inertias conected by three clutches)
https://www.claytex.com/tech-blog/investigating-events-in-your-dymola-model/attachment/coupledclutchesdemo/
Having just one fmu at time 0.4 we first have a time event, this time event triggers 2 state events, these state events triggers a third state event. With the proposed changes the first two state events cannot be handed until you finish your time event since you don't know about them. Instead you call getEventIndicators after the newDiscretStates and then you find your two first state events, call a new call to newDiscreteState to handle your stateEvent with rootsFinde[indx]= true, get a new root with eventIndicators, call newDiscreteStates again. 
With the current fmi2 interface the time event and the first state event can be handled in the same call. One could implement the function to handle all of them with the same call. 

So i propose that we scrap these arguments.

**Comment by andreas-junghanns** [comment] 2020-05-29 13:41
Less arguments? No arguments from me!

**Comment by otronarp** [comment] 2020-05-29 14:06
I think found (at least some of) the issues that is the reason why they were added: #588 and  #589. 

Basically for state events the motivation is to avoid conflicts if the master and FMU uses different epsilon for event hysteresis (https://github.com/modelica/fmi-standard/issues/588#issuecomment-515921263).

**Comment by chrbertsch** [comment] 2020-06-04 14:55
Regular Design Meeting: 

(Karl summarized) .... the only relevant information that I see is for state events, but this should  in fmi3NewDiscreteStates.
Otto: We need them then in fmi3enterEventMode also, because we do not call fmi3NewDiscreteStates before .... 
Karl: we need it  in fmi3NewDiscreteStates also, see a Coupled Clutches example, where events call different kind of events  ....
Otto: Are we sure about the time events? What about if master and slave do not agree on the time?
Otto: The FMU that handles the event has not detected it, so it would be good to tell the FMU what had happened.
Karl: for state events it's a mixture. The FMU provides the zero crossing
Torsten: Christian Schulze had an example ..... where it has a benefit. What is the problem with signalling what kind of events have been triggered?
Karl: Event indicators could change during event iteration ...
Torsten: is this true?
Karl: ... one can ignore this information. So why put much effort into supporting this?
Torsten: If one already knows which zero-crossing has been detected, so why not tell it to the FMU?
So the idea is just tell the FMU, why event mode is entered to work around tolerance issues.
Karl: is it a hint? or is it a requirement. Both have problems
Torsten: Could we make it a requirement for event indicators?
Karl: For time event and for state events one could make it mandatory. 
Torsten: for input events it is particularly interesting 
Karl: I cannot see this
....
Torsten: For state events it is helpful 
Karl: it is a special case. We do a special case implementation which introduces big changes to the interface.
Masoud: the main motivation for me was for time events due to different time accuracy
Karl: For time event it is no problem for me (still do not like it)
For input, step and state event I would pass the information in fmi3NewDiscreteStates.
Masoud: in event iteration we can have new zero crossings. 
Torsten: we discussed this a few weeks ago. The FMU does not know which zero crossings have been detected, only the master knows. This is valuable information for some implementation.
Otto: During event iteration, the FMU knows if it needs to iterate .... maybe it is confusing, but: 
fmi3entereventMode is a decision by the master, while requesing a new iteration is up to the FMU 
It is up to new FMU to detect state events and request new states. But at entering events, the FMU does not know know. But before there is an integration method  with zero crossing. But due to different epsilons we might have problems.
Masoud: for input events: if several FMUs are connected: If the first FMU is triggerd with a ... event, which triggers other FMUs by input events. So we have to update only FMUs that connected to this FMU.
Torsten: We are going in circles: if one updates everything one is always safe. Here it is about optimizations. We split the decision up

1.) Time events: OK --> Agreement (Karl: Abstain)

2.) Input events: 
Karl. Input changes are input events. 
Torsten: one can have other reasons
@masoud-najafi  and others: please provide rationale and example

3.)State events / passing of event indicators: 
Masoud it is an optimization; it may be ignored. 
Karl: then it has to be mandatory
Masoud: the Master has the information
Karls: why it is useful at enterEvent and not for fmi3NewDiscreteStates
Masoud:...
Torsten: the FMU cannot know what has been detected. Does not have to be mandatory; if there is NULL pointer you can ignore it?
Masoud: I would make it mandatory
Otto: In the past someone claimed that he cannot provide this information
Markus: Let's look at how this is done by solvers: Either tell which event indicator has been changed, or require that there is a sign change. One can covert the sign change to a flag.
Klaus:  It must be mandatory everywhere where we use it (also in fmi3NewDiscreteStates)
Klaus: we have confusion regarding the descirption of states (step events ....). This is not clear to non-Modelica-experts. In the description of this ticket, there might be confusion of step and state events.
Karl: I do not think so.
Masoud: step events can be called for any reason ... 
Markus: I think the question whether we need   an array of flags of event indicators  in fmi3NewDiscreteStates is a different polll. For fmi3EnterEventMode the situation is different, becaus previously  in continuous mode
Klaus: this is a difference between Modelia language and FMI
Markus: we have completetely parts: Master and slave (FMU). In later iterations in Event mode there is no information to change from master to the FMU
Klaus: I mostly agree.  We could ask the master to track event indicators even in event indicators. I think there are event indicators in event iterations.
Markus: **Event indicators should be only in continuous time** --> we have to clarify this 
Masoud, Christian: I agree
@klausschuch : I will create a ticket for this

Poll: Shall me make an array of flags of event indicators mandatory in fmi3EnterEventMode? 
Yes: Christian, Klaus, Markus, Masoud, Otto, Torsten, Karl
No:
Abstain: Matthias

@klausschuch : I will create a PR.

4. Step events
Klaus: The interpretation of step event  is not clear.  I cannot understand how a step event can occur within event iteration.
Markus: this is only meaningful if before one was in continuous time mode
Klaus: this is also written in the specification
Otto: It might happen later in event mode in an FMU, but it does not have to be signalled to the master.
Klaus: perhaps we can a little improve the the description of step events.

Masoud: what is the reason why to enter event iteration except time events?
Karl: e.g. for coupled clutches

Karl: what do we do if master and FMU do not agree detecting zero crossings ("epsilons")?
Klaus: this is not a new problem. It is up to the master. With the old version we could have left out events, because the epsilons did not match. So the new proposal is better. The FMU can do what it wants to do, but it has more information
Markus: I agree

Klaus: perhaps a smaller group should discuss this. @KarlWernersson : I will contact @HansOlsson ; @klausschuch : I also discussed this with a colleague . 

Klaus: the second part of the sentence "[These arguments are not mutually exclusive and may all be fmi3False if the caller cannot provide this information.]" shall be removed.

**Comment by andreas-junghanns** [comment] 2020-06-17 09:22
Outcome of discussion: Note that for HCS nEventIndicators is always 0.

**Comment by andreas-junghanns** [comment] 2020-06-17 09:31
We need to define/list all reasons for events (especially input events), for at least ME and HCS.

**Comment by andreas-junghanns** [comment] 2020-06-17 09:39
The flag for input event is the only way to transport the information that a continuous variable changed discretely.

**Comment by andreas-junghanns** [comment] 2020-06-17 09:46
For input events, we could even have a vector to show which input changed discretely.

**Comment by andreas-junghanns** [comment] 2020-06-17 10:39
Todo:
 - define all reasons for why an event iteration gets started, especially input events
 - explain the mechanism of detecting input events (See below)
 - explain the rational of the flags (optimization and information only) and use cases what to potentially do with this information (non-normative)
 - solve the epsilon issue (see #588) by modifying the reported crossing functions (adding a margin around 0), then the master can modify the values of the crossing function to use interpolation (Karl, Klaus and Hans know what they want to define here - we should add an example here for both master and FMU implementations)

Decision: we keep the flags, except the `fmi3Boolean inputEvent` which will be removed. After we enter the event mode, the change of any input variable is considered a discrete change and makes this event also an input event (this is the reason for dropping the inputEvent flag and remove redundant information).

Torsten: This might also be true/needed for FMI 2.0.2.

**Comment by CSchulzeTLK** [comment] 2020-06-17 14:07
I think it is good to be able to let the master decide about state events.

If the event indicators are not 100% reproducible (e.g. due to embedded solvers), then either the master needs to be informed by the FMU if an event had been triggered, or the master has to decide and inform the FMU about it.

I think the discussion I was involved in concluded, that this should be made optional if the master doesn't support it. However, I'm OK with making it mandatory. Since the protocol refers to "flags", I want to mention that an integer indicating the direction of sign change is less error prone.

**Comment by chrbertsch** [comment] 2020-06-26 11:14
Changing milestone to v3.0, as the 3.0alpha4 parts have already been merged.

**Comment by chrbertsch** [comment] 2020-08-28 14:44
Ticket-viewing-meeting

@klausschuch :  there is only one subtopic left that is covered by #588

**Closed by chrbertsch** 2020-08-28 14:44 UTC
Labels: PR_needed, discussion
