### ISSUE TITLE
FMI 3.0: Unit specification error regarding relativeQuantity

### ISSUE THREAD

**Issue by christoff-buerger** [modelica/fmi-standard#1165] opened 2020-09-05 12:38 UTC
In Section _2.2.2. Definition of Units_ the conversion of units based on `<BaseUnit>` is described.

One important pitfall is to incorporate the `offset` if `relativeQuantity="true"`; an example is given in subsection _Signal connection check_ which even refers to the definition of `relativeQuantity` below.

The problem now is, that the definition/description of `relativeQuantity` only talks about semantic means w.r.t. `displayUnit`:

> If this attribute is true, then the offset of displayUnit must be ignored. [For example, 10 degree Celsius = 10 Kelvin if relativeQuantity = true and not 283.15 Kelvin.]

I think, this is wrong. The `relativeQuantity` is much more important for the formal conversion of units based on `<BaseUnit>` definitions.

The definition of `relativeQuantity` should be respectively adapted. Also a more complex example how to use it for unit conversions has to be added.

Finally, the formula given for `<BaseUnit>`-based unit conversion should already incorporate `relativeQuantity`. At the moment it is just:

 > BaseUnit_value = factor * Unit_value + offset

but I guess it should be `BaseUnit_value = factor * Unit_value + (if relativeQuantity 0.0 else offset)`, although it now requires some linking to `relativeQuantity` which is not part of the `<Unit>`/`<BaseUnit>` definition itself but rather variable specific (it is an attribute of `<Float64Type>`, not `<BaseUnit>`).

**Comment by andreas-junghanns** [comment] 2020-09-09 11:29
@KarlWernersson & @TorstenBlochwitz : this sounds much like Modelica concepts. I tried to understand it from the text and without Modelica in mind, I cannot make sense of this. Can you both have a look and see how to formulate this with more clarity?

**Comment by KarlWernersson** [comment] 2020-09-09 12:58
I will try to explain it more simple. The problem is that relative quantity is defined to only apply to display unit but this is wrong, it must also apply to base unit.
Say that you have an output which is in degC. This output is a measured temperature difference. As it is defined now if you want to convert this difference to degK you have to add 273.15 as this is the offset. 
But a temperature difference Celsius is the same as the temperature difference in degK. 
Currently relative quantity would only apply to the display unit e.g if it had a display unit in degF, then you would not apply the 32 offset between degC and degF but you have to apply the offset to degK as the base  unit. A simple error in the standard.

Fix. change the definition of relative quantity, and the formula. 
Bonus fix, ad an example

**Comment by KarlWernersson** [comment] 2020-10-07 15:32
I will make a PR next week

**Comment by chrbertsch** [comment] 2020-10-20 13:41
Regular FMI Design Meeting:  @KarlWernersson: I will create PR until next week

**Comment by KarlWernersson** [comment] 2020-10-29 15:45
@chrbertsch 
This is a bug that should be fixed in 2.0.2 also

**Comment by chrbertsch** [comment] 2020-10-29 19:01
> This is a bug that should be fixed in 2.0.2 also

@KarlWernersson : I will do so when you have created a PR :-)

**Closed** 2020-11-06 15:59 UTC
Labels: PR_needed
