### ISSUE TITLE
String Variable XSD allows for multiple Start values?

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#838] opened 2020-03-09 13:11 UTC
The definition of fmy3String allows for multiple Start elements to be provided:
```
<xs:complexType name="fmi3String">
  <xs:complexContent>
    <xs:extension base="fmi3VariableBase">
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="Start">
          <xs:complexType>
            <xs:attribute name="value" type="xs:string">
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```
(Note the `maxOccurs="unbounded"`).

This allows the following ModelVariable:
```
<String name="somestring" valueReference="22222"
description="Some String" causality="input">
  <Start value="abc"/>
  <Start value="def"/>
  <Start value="hgk"/>
</String>
```

Am I missing something? I could not find information on Start values for strings, but I'm convinced that Start values have to be unique...

**Comment by friedrichatgc** [comment] 2020-03-09 13:19
For arrays of type string the start values (seperate start value for each element in the array variable) cannot be declared as a list of string in a single "value" attribute, as it is done for all other variable types. This is not possible since the space char cannot be the element seperator since space is a valid string char. That's why we decided to use a list fo "Start" elements for string and binary instead of a list for the "value" attribute.
Can you please check if this is documented probably in the specification and than close this issue.

**Comment by clagms** [comment] 2020-03-09 13:38
Thank you for the quick clarification @friedrichatgc !

>That's why we decided to use a list fo "Start" elements for string and binary instead of a list for the "value" attribute.

Indeed I found an example of this for <String> but, in the same example, a Binary var is declared as follows:
```
    <Binary name="Binary" valueReference="13" maxSize="28" start="3c3f 686572">
      <Dimension start="2"/>
    </Binary>
```
I guess then that the special rule for the Start element applies only to the type String.

The rule seems to be:
Inside a String element, if there are N dimension elements, each with start value Si (for i=1,...,N), then it is allowed to have \sum_{i=1}^{N} Si Start elements, following the row major order.
Is this correct?

I could not find this documented in the standard text.

**Comment by clagms** [comment] 2020-03-09 13:46
I guess the following is also forbidden, as there are two possible start values, right?
```
<String name="somestring" valueReference="22222"
description="Some String" causality="input" start="def">
  <Start value="abc"/>
</String>
```

So it must be one of the two following options:
```
<String name="somestring" valueReference="22222"
description="Some String" causality="input">
  <Start value="abc"/>
</String>
```
```
<String name="somestring" valueReference="22222"
description="Some String" causality="input" start="def">
</String>
```

Do we allow both? Or do we forbid the first option (we could say that Start element can only exist if there's a Dimension element).

**Comment by clagms** [comment] 2020-03-09 13:49
Thank you for the quick clarification @friedrichatgc !

>That's why we decided to use a list fo "Start" elements for string and binary instead of a list for the "value" attribute.

Indeed I found an example of this for <String> but, in the same example, a Binary var is declared as follows:
```
    <Binary name="Binary" valueReference="13" maxSize="28" start="3c3f 686572">
      <Dimension start="2"/>
    </Binary>
```
I guess then that the special rule for the Start element applies only to the type String.

The rule seems to be:
Inside a String element, if there are N dimension elements, each with start value Si (for i=1,...,N), then it is allowed to have \sum_{i=1}^{N} Si Start elements, following the row major order.
Is this correct?

I could not find this documented in the standard text.

**Comment by friedrichatgc** [comment] 2020-03-09 14:10
Partial duplicate of #513 which I have reopened.

**Comment by pmai** [comment] 2020-03-09 14:11
@clagms The rules are the same for all kinds of variables, the only difference is that string (and only string) start values are represented as seperate child elements, rather than an attribute with a list of values, for purely syntactic reasons (as @friedrichatgc explained, you can't have a list of strings in XML Schema).

I think what is missing in the current master branch is a place where the rules on the list of start values are laid down. There was text to this effect as far as I remember in the array proposal draft, but I don't seem to be able to find the equivalent in section 2.2, where I would have expected that.

**Closed by friedrichatgc** 2020-03-09 14:10 UTC
