### ISSUE TITLE
Should transitive dependencies between clocks be made explicit?

### ISSUE THREAD

**Issue by clagms** [modelica/fmi-standard#1621] opened 2022-01-10 08:52 UTC
Consider the following FMU:

![image](https://user-images.githubusercontent.com/871103/148739257-170e2d5e-06b6-4186-955b-9c641ce8f5d5.png)

While the picture does not show explicitly, there is a dependency between clock `c` and clock `d`,
because:
```
tick(c) => new_value(V) => maybe tick(d)
```

The question is: should the FMU be forced to declare such dependency in the model structure?

PS - Issued identified thanks to the work of @SimplisticCode

**Comment by andreas-junghanns** [comment] 2022-01-10 12:49
If `d` would have to be declared to depend also on `c` one would still need to keep the dependency on `v`, because `d` depends on both `c` being active and the value of `v`.

Is your question special to clocks? What about variables in the model structure that have such (transitive) relations?
If that is the case, would the `clocks` attribute then only be a subset of the variable dependencies?

**Comment by clagms** [comment] 2022-01-10 13:12
> If `d` would have to be declared to depend also on `c` one would still need to keep the dependency on `v`, because `d` depends on both `c` being active and the value of `v`.

Yes correct. 

> Is your question special to clocks?

I was thinking of clocks, but now that you mention it, it might be applicable to variables in general.

**Comment by KarlWernersson** [comment] 2022-01-10 15:19
Output clocks are listed in modelsStructure output
if v is a discrete state or an input it is listed in the dependencies, if it is not, v is computed from one or many discrete states and inputs and those will be listed in the dependency for the output clock instead.

**Comment by KarlWernersson** [comment] 2022-01-10 15:21
Closing?

**Comment by KarlWernersson** [comment] 2022-01-10 17:00
Sorry a bit hasty here to. My apologies

I will try alternative with a non clock variable.

Say that d is an output  that depends on v. /*e.g. through a hold operator if d is non clocked/*
For this case I would say it is sufficient to list its dependency on v. What you want to know is the equation structure for the d variable. That v is clocked can be deduced through its clock attribute and gives the hint that this dependency can be ignored when the clock of v is inactive.  

Expanding this to clocked output, I would say that the same logic hold an only explicit clock dependency should be listed. 

However the standard is not completely clear

> Attribute dependencies for output Clocks lists all known variables (including input clocks) that contribute to trigger a clock tick for that output Clock.

Is it sufficient to add an explicitly or do we need a bigger rewrite? 

Attribute dependencies for output Clocks lists all known variables (including input clocks) that explicitly contribute to trigger a clock tick for that output Clock.

**Comment by clagms** [comment] 2022-01-11 06:40
Thanks for the in-depth answer @KarlWernersson !

So what you are saying with 
> For this case I would say it is sufficient to list its dependency on v.

is that there transitive dependencies can be inferred by the Importer, and therefore the FMU does not have to list them.

> Is it sufficient to add an explicitly or do we need a bigger rewrite?

"Explicitly" might not be sufficient because it can mean different things. We can define explicit dependency as:
- `x` depends explicitly on `y` when `y` shows up at `x`'s assignment, 
- `x` depends implicitly on `y` when some other variable `w` that `x` depends explicitly on, depends (explicitly or implicitly) on `y`.


If we state that only explicit dependencies should be listed, then the importer will have to use both the `clocks` attribute and the model structure dependencies, to conclude in the above example, that `d` depends on `c`.
It clashes with the proposal I make in https://github.com/modelica/fmi-standard/issues/1620 to try and avoid using the `clocks` attribute to build dependency information and just use the model structure for that.

**Comment by andreas-junghanns** [comment] 2022-01-11 13:40
We worked hard to remove redundancies in the text and add links to related concepts to find definitions there.
I would kindly ask @clagms to check e.g. what is spelled out in file:///P:/fmi-standard/docs/index.html#dependencies to see if that isn't sufficient. And note (again): Clocks are variables like any other concerning `dependencies` (and note to note: this is not a coincident, but by design!).

So, disregarding the way the topic of this issue reads and generalizing to if "direct and indirect" dependencies must be documented in the modelDescription.xml, we should discuss here if the current text for `dependencies` is sufficient (and fix the issue heading).
As I read this, there is no concept of direct or indirect dependencies: dependencies are well defined and (numeric) variable types (clocks or not) do not matter, only their causality property is listed there.

Unless you find a fundamtental flaw in the current definition of the `dependencies`, I suggest to close this issue.
If you want to keep this open, please clearly state the issue beyond "direct vs. indirect".

**Comment by andreas-junghanns** [comment] 2022-01-12 10:14
In 2.4.8., definition of `dependencies` reads now: "Optional attribute defining the dependencies of the unknown vunknown (directly or indirectly via auxiliary variables)...". We will change "auxiliary" into "other", which should take care of this issue.

**Closed by andreas-junghanns** 2022-01-12 10:14 UTC
