### ISSUE TITLE
Clarification of calling SetClock for aperiodic output-clock

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/fmi-standard#1140] opened 2020-08-28 16:38 UTC
According to the table in section 2.1.8.5. (Setting and Getting Clock Activation State) , calling setClock is only allowed "if recomputations of clock state are needed during Event Mode".

I'm preparing an example for an FMU which has several input and output clocks. One of output clocks (clki) ticks aperiodically.

After ExitInitialization at t0, the FMU goes to the eventMode and sets internally clki and its corresponding next-tick time (interval).

After leaving fmi3NewDiscreteStates, the importer calls GetClock(clki) to check if clki has ticked.
If clki is fmi3Active, then the importer calls fmi3GetIntervalDecimal to retrieve the time of the next tick of clki (say it is t1).

The importer then calls  setClock(clki, fmi3ClockInactive) to deactivate the clock clki. (is this right? if yes, should be mentioned somewhere).

At t1, in order to retrieve the time of the next tick of clki, the importer pushes the FMU to the Event mode.
Should the importer call SetClock(clki, fmi3Active) to let the FMU know that the FMU has been called at clki's next tick (t1)?
But calling SetClock is forbidden for outputClocks.

**Comment by andreas-junghanns** [comment] 2020-08-29 06:56
> The importer then calls setClock(clki, fmi3ClockInactive) to deactivate the clock clki. (is this right? if yes, should be mentioned somewhere).

I don´t think this is correct, we even say:
"It is required for an FMU to directly internally set back the activation state of an output clock[i] to fmi3ClockInactive, if the function fmi3GetClock is called for a clock[i]..."
However, I am not sure, why the sentence continues with restricting this mechanism to SE:
"... and the interface is Scheduled Execution. [This is required to allow preemption.]"

I believe this should be true for all fmi3GetClock() calls: after the call, all clocks are set to inactive internally.
 
> At t1, in order to retrieve the time of the next tick of clki, the importer pushes the FMU to the Event mode.
The FMU is still in Event Mode.

> Should the importer call SetClock(clki, fmi3Active) to let the FMU know that the FMU has been called at clki's next tick (t1)?
> But calling SetClock is forbidden for outputClocks.

The SetClock(clki, fmi3Active) will be call on the FMU where clki is an input clock.
Why would you call SetClock on the same FMU that has clki as output clock (unless it has an input clock this output clock is connected to, regardless, if that would make any sense)?

**Comment by masoud-najafi** [comment] 2020-08-29 17:20
Concerning the first part, i.e., deactivating the clocks internally. Yes, that's all right.

Using setClock is just to avoid comparing times and to inform the FMU  that it is the tick of the output clock at t1.
Note that comparing clock times has never been a good idea, especially for "real" clocks due to the machine epsilon issue.

I noticed that the importer has to manage itself the local clocks of an FMU (for ModelExchange), i.e., the importer should call SetClock() and getClock() on clocks with causality Local. That said, if it is allowed to do setClock and getClock on local clocks, why not extend this to all clocks, i.e.,  the importer treats all clocks in the same way, regardless of their causality.
Input and output causality for clocks is just for connecting clock ports.

Otherwise I do not know how to make a simple aperiodic clock-generator-FMU work.

**Comment by masoud-najafi** [comment] 2020-08-29 18:12
Concerning the first part, i.e., deactivating the clocks internally. Yes, that's all right.

Using setClock is just to avoid comparing times and to inform the FMU  that it is the tick of the output clock at t1.
Note that comparing clock times has never been a good idea, especially for "real" clocks due to the machine epsilon issue.

I noticed that the importer has to manage itself the local clocks of an FMU (for ModelExchange), i.e., the importer should call  getClock() on clocks with causality Local. That said, if it is allowed to do getClock on local clocks, why not extend this to all clocks, i.e.,  the importer treats all clocks in the same way, regardless of their causality.
Input and output causality for clocks is just for connecting clock ports.
Otherwise I do not know how to make a simple aperiodic clock-generator-FMU work.

**Comment by andreas-junghanns** [comment] 2020-08-31 14:11
web design meeting:
Andreas: you should not call SetClock on output clocks.
Masoud: How to build an FMU with such an output clock.
TorstenB: It is a time-based aperiodic clock. Once the clock ticked, the importer must call the getInterval. Then the importer needs to raise an event at the correct time. Adding the interval in the importer might lead to numeric issues when that event is raised possibly slightly off. (this is a time event.) The FMU might miss, if an event was caused by its own output event.
Masoud: this is different from a zero-crossing event, that is executed immediately and has a different way of handling.
Andreas: Would you not need to make this also an input clock for such an event?
Karl: Ideally, those clocks must be also an input clock - to give the importer full control of the synchronous events.

... long discussion...

Massoud: I can try to discuss with TorstenB and Karl to find a solution.

**Comment by masoud-najafi** [comment] 2020-09-01 14:14
I think I found a solution based on the @andreas-junghanns  proposal.
I order to make a synchronous aperiodic (or even priodic) clock generator, we can proceed in this way:

1) The FMU defines an initial tick on an output-clock (clko), i.e., the <initial> attribute of clko is "exact".
 If the initial attribute is "exact", just after leaving the initializationMode, the importer calls GetClock(clko) and retrieves its initial tick time using getInterval(clko), say it is at t1.

2)At t1, the importer should propagate the clock tick of clko into ALL input clock ports of other FMUs connected to clko, i.e., the importer calls setClock(clkX[i]) on all connected clkX[i] input-clock ports. 

3)In order to recall the FMU a t1 to reprogram another tick on clko at t2, it is sufficient to connect clko to the input clock of FMU (clki). Then the importer includes clki in the list clkX. clko nan be interconnected externally with a clock link (i.e. an external loop see image) OR an internal link similar to the TriggeredBy attribute in SE. 
I prefer by far the external link which is easier to understand without loosing the generality.

For this solution, all we need is just this clarification on the initial attribute of output-clock:
In the Table 4 (Definition of initial), initial value of output-clock can only be set to "calculated" (it can be exact/approx/calculated for regular outputs). This example shows that we need to set initial=Exact on output-clock. 
If Initial=exact, the importer should call FMU after initialization and retrieved the output-clock tick time using getInterval().

What do you think about it?

**Comment by masoud-najafi** [comment] 2020-09-01 14:37
![image](https://user-images.githubusercontent.com/33484393/91865148-5fbe7b80-ec71-11ea-8430-01680a1678ff.png)

**Comment by andreas-junghanns** [comment] 2020-09-15 14:18
This is now explained and merged into master.

**Closed by andreas-junghanns** 2020-09-15 14:18 UTC
Labels: discussion
