### ISSUE TITLE
List license dependencies in FMI3.0

### ISSUE THREAD

**Issue by meek1** [modelica/fmi-standard#556] opened 2019-03-11 13:39 UTC
Make license dependencies clear in FMI3.0 so that users get this info prior to simulation, i.e. part of xml.

Could be treated as an external dependency in line with what is planned for source code FMUs (but this is for any FMU).

**Comment by beutlich** [comment] 2019-03-11 13:43
In addition to #417.

**Comment by KarlWernersson** [comment] 2019-03-11 16:57
Is the request to list which tool licences are required to be able to run the FMU (e.g. Dymola runt time license that is required for some Dymola fmus) or  which legal licenses that are needed to be accepted to run the fmu (e.g BSD license etc listed in the documentation section of Dymola fmus) ?

**Comment by meek1** [comment] 2019-03-11 17:51
I mean Dymola runt time license or similar. I could also imagine the opposite solution, i.e. something like a flag isLicenseFree or requiresRunTimeLicense.

**Comment by chrbertsch** [comment] 2019-03-11 19:40
This would be extremely useful for users. 
It would be also helpful to provide the name of the needed license features (e.g., runtime licenses, library licenses, ...), licenseing mechanism (e.g., flexlm). Perhaps such information is partilly very specific, so that it could be vendor annotations. 
Putting this information in the XML would enable checking/ configuring co-simulation setups.

**Comment by beutlich** [comment] 2019-03-12 07:17
I see. It rather is related to #438 and the loose definition of "self-contained".

**Comment by chrbertsch** [comment] 2019-03-22 16:23
Regular design meeting: 

Karl: would be good information to have, hard to automatize

Pierre: Could be also provided in the logging callback when an error is thrown. One could have a more explicit error information.  (A predefined category for this kind of error?)

Karl: in Dymola the information is given in the description string

Klaus: we would need a clear error code, when instantiation fails

Pierre: We do not have error codes for instantiation. That is why I propose a logging category.
(But in another place we decided against  a new category)

Poll:
Proposal: The FMU must add an optional attribute string "LicensingDependency" if it needs an external license: Karl
Proposal extended:  Additionally predefined logging category "Licensing": Christian B., Klaus,  Pierre, Kaska
Leave everythink unchanged: 
Abstain: Torsten S., Masoud

**Comment by chrbertsch** [comment] 2019-06-24 19:42
@meek1: could you please come up with a proposal for the wording ? Thanks!

**Comment by chrbertsch** [comment] 2020-02-29 20:45
Two main reasons prevent an FMU from being "self-contained"

- an installed tool is needed. This is addressed for CS FMUs by `needsExecutionTool`
- the generated FMU depends on some licensing mechanism like a flexlm licensing server.
This is currently not addressed in FMI2, and the topic of this issue.

Is see the following possibilities to improve the situation: 
* Provide this information in the documentation. Can be done already today. However, there is no standardized place where to put this.  But this is a very flexible solution and on can e.g. also include information whom to contact to get more information
* provide the information on in the modeldescriptionn.xml, with some optional flag `needsLicsening` analogous to the `needsExecutionTool`. Alternatively one could just define an optinal `LicensingDisplayText` (E.g. with the value `This FMU requires a runtime license of Tools XXX. Please provide the license server information in an environment variable as described in the documentation contained in the documentation folder of this FMU`
one could _at import time_ pop up a window hinting the user to set up the licensing.  This would help not so advanced users of FMI (and would avoid support calls "why is simulation of this FMU not possible"
More detailed information can be put in the documentation folder, see above
* Provide an error in a predefined  logging category "Licensing" as suggested above.

Perhaps the best would be the combination of all three suggestions. 
Any comments? (@meek1 etc.)

**Comment by andreas-junghanns** [comment] 2020-02-29 21:25
We have a license directory in the documentation directory. Import tools could how the license.txt or license.html file that are defined to be the entry points.

I am not sure we can manage to extend the XML to have proper license information formally defined for 3.0 (@meek1 did not provide a proposal for one entire year, I guess the issue is not pressing). I also believe that it is not simple to find a formalism to describe all kinds of licensing schemas out there properly in a short time.

I propose to close this issue, or at least postpone it to 3.1.

**Comment by chrbertsch** [comment] 2020-03-01 19:28
> We have a license directory in the documentation directory. Import tools could how the license.txt or license.html file that are defined to be the entry points.

Citing from 2.3: ` The sub-directory "licenses" can be used to bundle all license files.` 
This subdirectory is currently intended only to be used for _license texts_ (e.g. BSD license text for some library)` 

@meek1 's concern is about necessary _licensing information_.
If we would have in the modeldescriptoin.xml a flag `needsLicsening `, an importing tool could at import display automatically a file license.html (if we change the text of 2.3 defining that such information shall be also contained there or a newly defined licensing.html file or the index.html file (with a hint in 2.3 that licensing information can be found there.
This would help users a lot, as many FMUs require runtime licenses (e.g., Dymola FMUs for users w/o SourceCodeExport licesene, AMESim FMUs, GT-Suite FMUs, ETAS ISOLAR-EVE FMUs, ....)s

**Comment by meek1** [comment] 2020-03-01 19:38
Agree, runtime licenses violates the ”self-contained” vision of FMI, and if a FMU needs a license this should be clearly stated and easy to check prior to importing, composing, and trying to simulate FMUs.

A boolean needsLicensing, or needsRuntimeLicensing, would help users alot.

**Comment by andreas-junghanns** [comment] 2020-03-01 21:21
To include runtime licenses into the semantics of "self-contained" is debatable.
At least I was so far considering only code and data meant as "self-contained".
Counting run-time licenses also would be new to me.
We never distinguished between build and run-time license before and legally there is no difference, really. So if we now make room for the description of run-time licenses, will the user not assume that no other licenses are needed/effected?

I agree that @meek1´s concern is about ease of use. But is that sufficient?
Should we not list all licenses and mark them as both build and run-time?

**Comment by chrbertsch** [comment] 2020-03-01 21:45
> To include runtime licenses into the semantics of "self-contained" is debatable.

I do not find a definition of "self contained" in our specification. Perhaps we should add some :-)

As a user when exchanging an FMU with some I have to check the following points (beyond suitability of the FMU-type and its numerical properties)
- does the FMU contain the right binaries or source code --> transparent in the zip-file
- am I legally allowed to pass this FMU to a third party:  --> in FMI 3.0, this information can be provided in ./documentation/licenses . Beyond OSS licenses used by the FMU this can also be a license text of the exporting tool restricting the usage of the FMU
- do I have to install a tool on the target machine? --> at least for CS this visible from the needsExecutionTool flag. 
- do I need a runtime license and/or set up connection to  a license server? --> this is not covered yet and the topic of this issue.  I would not heavily automatize this, but help the user by introducing a new flag and pointing him to the documentation.

>Should we not list all licenses and mark them as both build and run-time? 
licenses in the ./documentation/licenses folder refer to legal texts currently and not documentation on licensing mechanism and whom to contact to get a license. But perhaps we can extend this to provide the missing information

**Comment by andreas-junghanns** [comment] 2020-03-01 22:13
Excellent overview!
Agreed.
Can we simply have a second folder under ./documentation/, say /run-time-licenses with the specific requirement to list all run-time licenses. How? One per file inside? Just text, just for display? We cannot solve all kinds of license issues automatically, right?

**Comment by pmai** [comment] 2020-03-01 22:30
If the goal is to make it easy to find out what is needed in order to run the FMU, should this not be part of the documentation, potentially under a specific path (similar to @andreas-junghanns suggestion)? I think runtime license manager dependencies are only a very partial subset of runtime requirements that might need to be fulfilled (consider FMUs that connect to network resources, memory requirements, ...).

A flag in modelDescription does not seem like a useful approach to this.

**Comment by chrbertsch** [comment] 2020-03-01 22:38
> If the goal is to make it easy to find out what is needed in order to run the FMU, should this not be part of the documentation, potentially under a specific path (similar to @andreas-junghanns suggestion)? I think runtime license manager dependencies are only a very partial subset of runtime requirements that might need to be fulfilled (consider FMUs that connect to network resources, memory requirements, ...).
> 
> A flag in modelDescription does not seem like a useful approach to this.

That would be fine for me.

I think one file is sufficient, at least as entry point.
This would be an optional file with a standardized name, e.g. ./documentation/runtime-licensing-info.html
(I would use "licensing" instead of "licenses", as in license files I would expect legal texts.)

When an FMU gets imported, the importing tool could display this file - if present - to help the user.

**Comment by chrbertsch** [comment] 2020-03-02 07:13
> A flag in modelDescription does not seem like a useful approach to this.

However, it would be analogous to the `needsExecutionTool` flag. 
Or what is the difference? 
And how do importing tools today make use of this flag?

**Closed** 2021-07-21 14:59 UTC
Labels: enhancement
