### ISSUE TITLE
Fix variable types for fmi3SetXXX and fmi3GetXXX in specification text

### ISSUE THREAD

**Issue by chrbertsch** [modelica/fmi-standard#696] opened 2019-12-29 19:08 UTC
In many places in the specification text there are still the fmi2-style. versions of variable types used (i.e. fmi3SetReal instead of fmi3SetFloat64.

**Comment by t-sommer** [comment] 2019-12-29 23:10
This is a duplicate of #669

**Closed by t-sommer** 2019-12-29 23:10 UTC
Labels: duplicate
