### ISSUE TITLE
FMI fmi2CallbackFunctions struct is defined from FMU point of view (const), importer needs non-const

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/fmi-standard#443] opened 2018-10-17 01:20 UTC
**Reported by federico&#x2e;terraneo on 6 Oct 2018 09:28 UTC**
fmi2FunctionTypes.h contains the following code

typedef struct {

    const fmi2CallbackLogger logger;
    const fmi2CallbackAllocateMemory allocateMemory;
    const fmi2CallbackFreeMemory freeMemory;
    const fmi2StepFinished stepFinished;
    const fmi2ComponentEnvironment componentEnvironment;

} fmi2CallbackFunctions;

where all fields are declared const. However in C++ const fields in structs/classes can only be initialized in a constructor's intialization list, and the struct has no constructor. I think const should be removed to make this code interoperable with C++.

This issue has been reported to OpenModelica first https://trac.openmodelica.org/OpenModelica/ticket/5152
but apparently this file is part of the FMI standard.

----

Migrated-From: https://trac.fmi-standard.org/ticket/443

**Comment by pmai** [comment] 2018-10-27 08:59
For what it's worth the header files are currently geared only toward the FMU interface itself, i.e. they are not really useful for the implementation calling the FMU: For the FMU code, it only ever needs to access the members of this struct (passed by pointer), so initialization issues are not relevant. In this case the const protection prevents the FMU from changing the member function pointers, which is the intention.

This consequently means that importing tools will usually need to use different header files/data sets to actually generate the struct (e.g. by using a non-const version of the struct and casting). This is of course a bit cumbersome, and might not way lightly against the perceived benefit of const protection.

In any case this is not a bug, in that it is done by design and the consequences are known and can be handled properly by tools (i.e. the original OpenModelica problem still looks an OpenModelica bug to me, since that code seems to want to instantiate an fmi2CallbackFunctions variable itself, which of course you cannot do).
I think this issue should be adressed one way or another (i.e. either stay with the current definition, or abandon constness) for 3.0 by poll.

**Comment by andreas-junghanns** [comment] 2019-01-29 15:16
Klaus: We could change the definition of the structure to change depending on import/export.
Andreas: We could have two struct definitions for each direction. But casting is a mess.
Karl: Remove the const from the elements, but change the function definition to make that parameter const.

Action: Pierre will investigate if Karl's proposal is the solution to the original problem (not changing by the FMU, but keep type safety (no casting)).

**Comment by pmai** [comment] 2019-01-29 19:03
I've rechecked this, and the change (remove const qualifiers on struct members, keep pointer to const qualifier in fmi3Instantiate), as already implemented and merged in #508 for FMI 3.0, works as intended both on C and C++.

We just need to affirm this change by poll, and decide whether to perform the same improvement for 2.0.1 (see #216).

**Comment by KarlWernersson** [comment] 2019-02-12 13:36
It was decided at the design meeting 2019-02-12 to go with this correction.

**Comment by KarlWernersson** [comment] 2019-06-20 10:40
Is, fmi3Instantiate also updated?
Can it then be closed?

**Comment by chrbertsch** [comment] 2020-02-29 13:51
This has long been fixed with https://github.com/modelica/fmi-standard/commit/b74b949caeab4358293c4911a94e9fdff6405788#diff-3a2dd90ddbfbffbadd2fb2731ec4a1c7

**Closed by chrbertsch** 2020-02-29 13:51 UTC
Labels: duplicate, task
